import { useEffect, useState } from 'react';
import DashboardShell from '../../components/dashboard/DashboardShell';
import { patientSidebarItems } from '../../data/patientNavigation';
import { getDoctors } from '../../services/doctorService';
import { bookAppointment } from '../../services/appointmentService';

export default function BookAppointment() {
  const [doctors, setDoctors] = useState([]); const [specialization, setSpecialization] = useState(''); const [search, setSearch] = useState(''); const [selected, setSelected] = useState(null); const [form, setForm] = useState({ date: '', timeSlot: '', notes: '' }); const [message, setMessage] = useState('');
  useEffect(() => { getDoctors().then(setDoctors).catch(() => setMessage('Unable to load doctors.')); }, []);
  const filteredDoctors = doctors.filter(d => `${d.userId?.name || ''} ${d.specialization || ''}`.toLowerCase().includes(`${search} ${specialization}`.trim().toLowerCase()));
  const submit = async (e) => { e.preventDefault(); if (!selected) return setMessage('Select a doctor first.'); try { await bookAppointment({ doctorId: selected.userId._id, ...form }); setMessage('Appointment request submitted. The doctor will accept or reject it.'); setSelected(null); } catch (err) { setMessage(err.response?.data?.message || 'Could not create appointment.'); } };
  return <DashboardShell title="Book appointment" sidebarItems={patientSidebarItems}><div className="grid gap-6 xl:grid-cols-[1fr_.8fr]"><section className="rounded-3xl bg-white p-6 shadow-sm"><h1 className="text-2xl font-bold">Find the right doctor</h1><div className="mt-4 grid gap-3 sm:grid-cols-2"><input className="w-full rounded-xl border p-3" placeholder="Search doctor" value={search} onChange={e => setSearch(e.target.value)} /><input className="w-full rounded-xl border p-3" placeholder="Filter speciality" value={specialization} onChange={e => setSpecialization(e.target.value)} /></div><div className="mt-5 space-y-3">{filteredDoctors.map(d => <button type="button" key={d._id} onClick={() => setSelected(d)} className={`w-full rounded-2xl border p-4 text-left ${selected?._id === d._id ? 'border-brand-500 bg-brand-50' : ''}`}><p className="font-semibold">Dr. {d.userId?.name}</p><p className="text-sm text-slate-500">{d.specialization} · {d.experience} · ₹{d.consultationFee}</p></button>)}{!filteredDoctors.length && <p className="text-slate-500">No approved doctors match this filter.</p>}</div></section><section className="rounded-3xl bg-white p-6 shadow-sm"><h2 className="text-xl font-bold">Request appointment</h2><p className="mt-2 text-sm text-slate-500">{selected ? `With Dr. ${selected.userId?.name}` : 'Choose a doctor to continue.'}</p><form onSubmit={submit} className="mt-5 space-y-4"><input required type="date" min={new Date().toISOString().slice(0,10)} className="w-full rounded-xl border p-3" onChange={e => setForm({...form, date:e.target.value})}/><input required placeholder="Preferred time (e.g. 10:30 AM)" className="w-full rounded-xl border p-3" onChange={e => setForm({...form, timeSlot:e.target.value})}/><textarea placeholder="Reason for visit (optional)" className="w-full rounded-xl border p-3" onChange={e => setForm({...form, notes:e.target.value})}/><button className="w-full rounded-xl bg-brand-600 p-3 font-semibold text-white">Submit request</button></form>{message && <p className="mt-4 text-sm text-brand-800">{message}</p>}</section></div></DashboardShell>;
}
